import { IMAGE_URL } from "@nyx-frontend/main/components/constants";
import { nanoid } from "nanoid";

export const creatorOptions = [
  { value: "socialMediaPost", label: "Social Media Post" },
  { value: "Banner Ads", label: "Banner Ads" },
  { value: "Display Image", label: "Display Image" },
  { value: "Email Marketing Image", label: "Email Marketing Image" },
];
export const brandPaintingOptions = [
  { value: "Open with Brand Canvas", label: "Open with Brand Canvas" },
  { value: "Open with Image to Video", label: "Open with Image to Video" },
];
export const size = [
  { value: "1:1", label: "1:1" },
  { value: "3:2", label: "3:2" },
  { value: "16:9", label: "16:9" },
  { value: "4:3", label: "4:3" },
  { value: "5:4", label: "5:4" },
];
export const resolution = [
  { value: "1024x1024", label: "1024x1024" },
  { value: "1152x896", label: "1152x896" },
  { value: "1216x832", label: "1216x832" },
  { value: "1344x768", label: "1344x768" },
  { value: "1536x640", label: "1536x640" },
  { value: "640x1536", label: "640x1536" },
  { value: "768x1344", label: "768x1344" },
  { value: "832x1216", label: "832x1216" },
  { value: "896x1152", label: "896x1152" },
];
export const event = [
  { value: "newYearsale", label: "New Year Sale" },
  { value: "newYear", label: "New Year" },
  { value: "Diwali", label: "Diwali" },
  { value: "Holi", label: "Holi" },
  { value: "Navratri", label: "Navratri" },
  { value: "Janmashtmi", label: "Janmashtmi" },
  { value: "Independence Day", label: "Independence day" },
  { value: "Republic Day", label: "Republic Day" },
];
export const colours = [
  { value: "black", label: "Black" },
  { value: "white", label: "White" },
  { value: "Blue", label: "Blue" },
  { value: "Green", label: "Green" },
  { value: "Yellow", label: "Yellow" },
  { value: "Orange", label: "Orange" },
  { value: "Red", label: "Red" },
  { value: "Brown", label: "brown" },
];

export const ruleFilter = [
  { value: "Hour", label: "Hour" },
  { value: "Day", label: "Day" },
  { value: "Week", label: "Week" },
  { value: "Month", label: "Month" },
];

export const ruleStatus = [
  { value: "ALL", label: "All" },
  { value: "ACTIVE", label: "Active" },
  { value: "INACTIVE", label: "Inactive" },
];

export const vibe = [
  { value: "Serene", label: "Serene" },
  { value: "Energetic", label: "Energetic" },
  { value: "Cozy", label: "Cozy" },
  { value: "Playful", label: "Playful" },
  { value: "Sophisticated", label: "Sophisticated" },
  { value: "Adventurous", label: "Adventurous" },
  { value: "Inspirational", label: "Inspirational" },
  { value: "Whimsical", label: "Whimsical" },
  { value: "Minimalistic", label: "Minimalistic" },
  { value: "Vintage", label: "Vintage" },
  { value: "Urban", label: "Urban" },
  { value: "Romantic", label: "Romantic" },
  { value: "Futuristic", label: "Futuristic" },
  { value: "Natural", label: "Natural" },
  { value: "Dynamic", label: "Dynamic" },
  { value: "Mystical", label: "Mystical" },
  { value: "Bold", label: "Bold" },
  { value: "Tranquil", label: "Tranquil" },
  { value: "Nostalgic", label: "Nostalgic" },
  { value: "Wholesome", label: "Wholesome" },
];
export const proximity = [
  { value: "Close Up", label: "Close Up" },
  { value: "Telephoto", label: "Telephoto" },
  { value: "Wide Angle", label: "Wide Angle" },
  ,
];
export const position = [
  { value: "overhead", label: "Overhead" },
  { value: "Low angle", label: "Low Angle" },
  { value: "Human Level Perspective", label: "Far " },
  { value: "Low Angle Perspective", label: "Low Angle Perspective" },
  { value: "High Angle Perspective", label: "High Angle Perspective" },
  { value: "Aerial view", label: "Aerial view" },
  { value: "Tilted Frame", label: "Tilted Frame" },
];
export const shutterSettings = [
  { value: "Fast Shutter Speed", label: "Fast Shutter Speed" },
  { value: "Medium Shutter Speed", label: "Medium Shutter Speed" },
  { value: "Slow Shutter speed", label: "Slow Shutter speed" },
  { value: "Bokeh", label: "Bokeh" },
  ,
];
export const creativeFilmFilter = [
  { value: "Kodachrome", label: "Kodachrome" },
  { value: "autochrome", label: "Autochrome" },
  { value: "Lomography", label: "Lomography" },
  { value: "Polaroid", label: "Polaroid" },
  { value: "CCTV", label: "CCTV" },
  { value: "Disposable", label: "Disposable" },
  { value: "Daguerrotype", label: "Daguerrotype" },
  { value: "Obscura", label: "Obscura" },
  { value: "Cameraphone", label: "Cameraphone" },
  { value: "Cameraphone", label: "Cameraphone" },
  { value: "Cyanotyoe", label: "Cyanotyoe" },
  { value: "Black and White", label: "Black and White" },
  { value: "Rescale phototype", label: "Rescale phototype" },
  { value: "Infrared", label: "Infrared" },
  { value: "Bleach bypass", label: "Bleach bypass" },
  { value: "Instagram Contact sheet", label: "Instagram Contact sheet" },
  { value: "Colour splash", label: "Colour splash" },
  { value: "Solarised", label: "Solarised" },
  { value: "Anaglaph", label: "Anaglaph" },
  ,
];
export const lighting = [
  { value: "outDoorLighting", label: "Out Door Lighting" },
  { value: "inDoorLighting", label: "Indoor Lighting" },
];
export const outdoorLightingOptions = [
  { value: "outDoor", label: "Out Door" },
  { value: "Golden hour", label: "Golden hour" },
  { value: "Blue hour", label: "Blue hour" },
  { value: "Midday", label: "Midday" },
  { value: "Overcast", label: "Overcast" },
  { value: "Silhouette", label: "Silhouette" },
];
export const indoorLightingOptions = [
  { value: "Warm Lighting", label: "Warm Lighting" },
  { value: "cold", label: "cold" },
  { value: "flash photo", label: "flash photo" },
  { value: "Colourful Lighting", label: "Colourful Lighting" },
  { value: "High key Lighting", label: "High key Lighting" },
  { value: "Low key Lighting", label: "Low key Lighting" },
  { value: "Backlighting", label: "Backlighting" },
  { value: "Studio Lighting", label: "Studio Lighting" },
];

// export const category = [
//   { value: "ConsumerGoods", label: "Consumer Goods" },
//   { value: "Technology", label: "Technology" },
//   { value: "Automotive", label: "Automotive" },
//   { value: "FashionAndApparel", label: "Fashion and Apparel" },
//   { value: "HealthcareAndPharma", label: "Healthcare and Pharma" },
//   { value: "RetailAndECommerce", label: "Retail and E-commerce" },
//   { value: "EntertainmentAndMedia", label: "Entertainment and Media" },
//   { value: "FinancialServices", label: "Financial Services" },
//   { value: "TravelAndHospitality", label: "Travel and Hospitality" },
//   { value: "FoodAndBeverage", label: "Food and Beverage" },
//   { value: "RealEstate", label: "Real Estate" },
//   { value: "Telecommunications", label: "Telecommunications" },
//   { value: "HomeAndLifestyle", label: "Home and Lifestyle" },
//   { value: "SportsAndFitness", label: "Sports and Fitness" },
//   { value: "Education", label: "Education" },
//   { value: "NonProfitAndSocialCauses", label: "Nonprofit and Social Causes" },
//   { value: "BeautyAndCosmetics", label: "Beauty and Cosmetics" },
//   { value: "EnergyAndUtilities", label: "Energy and Utilities" },
//   { value: "AgricultureAndFarming", label: "Agriculture and Farming" },
//   {
//     value: "GovernmentAndPublicServices",
//     label: "Government and Public Services",
//   },
//   {
//     value: "RealEstateAndReits",
//     label: "Real Estate and Real Estate Investment Trusts (Reits)",
//   },
//   { value: "RecruitmentAndStaffing", label: "Recruitment and Staffing" },
//   { value: "LuxuryHospitality", label: "Luxury Hospitality" },
//   { value: "MediaAndJournalism", label: "Media and Journalism" },
//   { value: "GamingAndEsports", label: "Gaming and Esports" },
//   { value: "EnvironmentalServices", label: "Environmental Services" },
//   {
//     value: "ManufacturingAndProduction",
//     label: "Manufacturing and Production",
//   },
//   {
//     value: "ConstructionAndRealEstateDevelopment",
//     label: "Construction and Real Estate Development",
//   },
//   {
//     value: "HomeImprovementAndRenovation",
//     label: "Home Improvement and Renovation",
//   },
//   {
//     value: "DigitalMarketingAndAdvertising",
//     label: "Digital Marketing and Advertising",
//   },
//   {
//     value: "EventManagementAndPlanning",
//     label: "Event Management and Planning",
//   },
//   { value: "Cybersecurity", label: "Cybersecurity" },
//   {
//     value: "TransportationAndLogistics",
//     label: "Transportation and Logistics",
//   },
//   { value: "TelevisionAndBroadcasting", label: "Television and Broadcasting" },
//   { value: "CateringAndFoodServices", label: "Catering and Food Services" },
//   { value: "ResearchAndDevelopment", label: "Research and Development" },
//   { value: "FinanceAndBanking", label: "Finance and Banking" },
//   { value: "InformationTechnology", label: "Information Technology" },
//   { value: "Insurance", label: "Insurance" },
//   { value: "ArtAndCulture", label: "Art and Culture" },
//   { value: "SoftwareDevelopment", label: "Software Development" },
//   { value: "PhotographyAndVideography", label: "Photography and Videography" },
//   { value: "QuickCommerce", label: "Quick Commerce" },
// ];

export const category = [
  { value: "automobiles", label: "Automobiles" },
  { value: "electronics", label: "Electronics" },
  { value: "finance_and_banking", label: "Finance and Banking" },

  {
    value: "ecommerce",
    label: "Ecommerce",
  },
  {
    value: "entertainment_and_media",
    label: "Entertainment and Media",
  },
  {
    value: "food_and_beverages",
    label: "Food and Beverages",
  },
  {
    value: "gaming",
    label: "Gaming",
  },
  {
    value: "edtech",
    label: "Edtech",
  },
  {
    value: "cosmetics",
    label: "Cosmetics",
  },

  // { value: "ConsumerGoods", label: "Consumer Goods" },
  // { value: "Technology", label: "Technology" },
  // { value: "Automotive", label: "Automotive" },
  // { value: "FashionAndApparel", label: "Fashion and Apparel" },
  // { value: "HealthcareAndPharma", label: "Healthcare and Pharma" },
  // { value: "RetailAndECommerce", label: "Retail and E-commerce" },
  // { value: "EntertainmentAndMedia", label: "Entertainment and Media" },
  // { value: "FinancialServices", label: "Financial Services" },
  // { value: "TravelAndHospitality", label: "Travel and Hospitality" },
  // { value: "FoodAndBeverage", label: "Food and Beverage" },
  // { value: "RealEstate", label: "Real Estate" },
  // { value: "Telecommunications", label: "Telecommunications" },
  // { value: "HomeAndLifestyle", label: "Home and Lifestyle" },
  // { value: "SportsAndFitness", label: "Sports and Fitness" },
  // { value: "Education", label: "Education" },
  // { value: "NonProfitAndSocialCauses", label: "Nonprofit and Social Causes" },
  // { value: "BeautyAndCosmetics", label: "Beauty and Cosmetics" },
  // { value: "EnergyAndUtilities", label: "Energy and Utilities" },
  // { value: "AgricultureAndFarming", label: "Agriculture and Farming" },
  // {
  //   value: "GovernmentAndPublicServices",
  //   label: "Government and Public Services",
  // },
  // {
  //   value: "RealEstateAndReits",
  //   label: "Real Estate and Real Estate Investment Trusts (Reits)",
  // },
  // { value: "RecruitmentAndStaffing", label: "Recruitment and Staffing" },
  // { value: "LuxuryHospitality", label: "Luxury Hospitality" },
  // { value: "MediaAndJournalism", label: "Media and Journalism" },
  // { value: "GamingAndEsports", label: "Gaming and Esports" },
  // { value: "EnvironmentalServices", label: "Environmental Services" },
  // {
  //   value: "ManufacturingAndProduction",
  //   label: "Manufacturing and Production",
  // },
  // {
  //   value: "ConstructionAndRealEstateDevelopment",
  //   label: "Construction and Real Estate Development",
  // },
  // {
  //   value: "HomeImprovementAndRenovation",
  //   label: "Home Improvement and Renovation",
  // },
  // {
  //   value: "DigitalMarketingAndAdvertising",
  //   label: "Digital Marketing and Advertising",
  // },
  // {
  //   value: "EventManagementAndPlanning",
  //   label: "Event Management and Planning",
  // },
  // { value: "Cybersecurity", label: "Cybersecurity" },
  // {
  //   value: "TransportationAndLogistics",
  //   label: "Transportation and Logistics",
  // },
  // { value: "TelevisionAndBroadcasting", label: "Television and Broadcasting" },
  // { value: "CateringAndFoodServices", label: "Catering and Food Services" },
  // { value: "ResearchAndDevelopment", label: "Research and Development" },
  // { value: "FinanceAndBanking", label: "Finance and Banking" },
  // { value: "InformationTechnology", label: "Information Technology" },
  // { value: "Insurance", label: "Insurance" },
  // { value: "ArtAndCulture", label: "Art and Culture" },
  // { value: "SoftwareDevelopment", label: "Software Development" },
  // { value: "PhotographyAndVideography", label: "Photography and Videography" },
  // { value: "QuickCommerce", label: "Quick Commerce" },
  // { value: "FastFood", label: "Fast Food" },
  // { value: "PackagedFoods", label: "Packaged Foods" },
  // { value: "Consultancy", label: "Consultancy" },
  // { value: "Spirituality", label: "Spirituality" },
  // { value: "RentalServices", label: "Rental Services" },
  // { value: "BooksAndPublications", label: "Books and Publications" },
  // { value: "SocialOrganizations", label: "Social Organizations" },
  // { value: "Logistics", label: "Logistics" },
  // { value: "AdvertisingAndSales", label: "Advertising and Sales" },
  // { value: "TobaccoProducts", label: "Tobacco Products" },
  // { value: "Miscellaneous", label: "Miscellaneous" },
  // { value: "ProfessionalServices", label: "Professional Services" },
  // { value: "ElectricalEquipments", label: "Electrical Equipment" },
  // { value: "FashionAccessories", label: "Fashion Accessories" },
  // { value: "ElectronicAppliances", label: "Electronic Appliances" },
  // { value: "IndustrialEquipments", label: "Industrial Equipment" },
  // { value: "ComputersAndPeripherals", label: "Computers and Peripherals" },
  // { value: "Mobility", label: "Mobility" },
  // {
  //   value: "SmartphonesAndMobileDevices",
  //   label: "Smartphones and Mobile Devices",
  // },
  // {
  //   value: "ecommerce",
  //   label: "Ecommerce",
  // },
];

export const admanager_upload_media_type = [
  { value: "Image", label: "Image" },
  { value: "Video", label: "Video" },
];

const AGE_GROUP = Array(62)
  .fill(undefined)
  .map((_, i) => i + 18);

export const ageGroup2 = AGE_GROUP.map((e, i) => ({
  value: e,
  label: e,
}));

export const ageGroup = [
  {
    value: "Teens (18-19 years)",
    label: "Teens (18-19 years)",
    range: "18-19 years",
  },
  {
    value: "Young Adults (20-24 years)",
    label: "Young Adults (20-24 years)",
    range: "20-24 years",
  },
  {
    value: "Adults (25-54 years)",
    label: "Adults (25-54 years)",
    range: "25-54 years",
  },
  {
    value: "Seniors (55-65 years)",
    label: "Seniors (55-65 years)",
    range: "55-65 years",
  },
];

export const gender_ADmanager = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "All", label: "All" },
];

export const ageArray_ADmanager = Array.from(
  { length: 65 - 18 + 1 },
  (_, i) => ({
    value: (18 + i).toString(),
  })
);

export const ageGroup_ADmanager = [
  // { value: "All Ages", label: "All Ages", range: "All Ages" },
  // {
  //   value: "Infants (0-1 year)",
  //   label: "Infants (0-1 year)",
  //   range: "0-1 year",
  // },
  // { value: "Toddlers (1-3 years)", label: "Toddlers (1-3 years)", range: "1-3 years" },
  // {
  //   value: "Preschoolers (3-5 years)",
  //   label: "Preschoolers (3-5 years)",
  //   range: "3-5 years",
  // },
  // {
  //   value: "Early Childhood (6-8 years)",
  //   label: "Early Childhood (6-8 years)",
  //   range: "6-8 years",
  // },
  // {
  //   value: "Middle Childhood (9-11 years)",
  //   label: "Middle Childhood (9-11 years)",
  //   range: "9-11 years",
  // },
  // {
  //   value: "Preteens (12-13 years)",
  //   label: "Preteens (12-13 years)",
  //   range: "12-13 years",
  // },
  // {
  //   value: "Teens (13-19 years)",
  //   label: "Teens (13-19 years)",
  //   range: "13-19 years",
  // },

  {
    value: "Teens (18-19 years)",
    label: "Teens (18-19 years)",
    range: "18-19 years",
  },
  {
    value: "Young Adults (20-24 years)",
    label: "Young Adults (20-24 years)",
    range: "20-24 years",
  },
  {
    value: "Adults (25-54 years)",
    label: "Adults (25-54 years)",
    range: "25-54 years",
  },
  {
    value: "Seniors (55-65 years)",
    label: "Seniors (55-65 years)",
    range: "55-65 years",
  },
];

export const assetSortOptions = [
  { value: "Sort By", label: "Sort By(Default)", id: "-1" },
  { value: "Name", label: "Name", id: "0" },
  { value: "Date", label: "Date", id: "1" },
  { value: "Size", label: "Size", id: "2" },
];
// export const campaignStatusSort = [
//   { value: "UNDER_REVIEW", label: "Under Review" },
//   { value: "DRAFT", label: "Draft" },
//   { value: "INACTIVE", label: "Inactive" },
//   // { value: "ENABLED", label: "Enabled" },
//   { value: "ACTIVE", label: "Active" },
//   { value: "REJECTED", label: "Rejected" },
//   { value: "PAUSED", label: "Paused" },
//   { value: "All CAMPAIGNS", label: "All Campaigns" },
// ];
// export const campaignChannelSort = [
//   { value: "Facebook", label: "Facebook" },
//   { value: "Instagram", label: "Instagram" },
//   { value: "LinkedIn", label: "LinkedIn" },
//   { value: "Google", label: "Google" },
// ];
// export const campaignTimeSort = [
//   { value: "Oldest", label: "Oldest" },
//   { value: "Newest", label: "Newest" },
// ];

export const campaignStatusSort = [
  { value: "UNDER_REVIEW", label: "Under Review" },
  { value: "DRAFT", label: "Draft" },
  { value: "INACTIVE", label: "Inactive" },
  // { value: "ENABLED", label: "Enabled" },
  { value: "ACTIVE", label: "Active" },
  { value: "REJECTED", label: "Rejected" },
  { value: "PAUSED", label: "Paused" },
  { value: null, label: "All Campaigns" },
];
export const campaignChannelSort = [
  { value: "Facebook", label: "Facebook" },
  { value: "Instagram", label: "Instagram" },
  { value: "LinkedIn", label: "LinkedIn" },
  { value: "Google", label: "Google" },
];
export const campaignTimeSort = [
  { value: "asc", label: "Oldest" },
  { value: "desc", label: "Newest" },
];

export const assetFilterOptions = [
  { value: "Filter", label: "Filter (Default)", id: "-1" },
  { value: "Favourite", label: "Favourite", id: "0" },
];

export const audienceOptions = [
  { value: "Do Not Send", label: "Do Not Send", id: "-1" },
  { value: "Email Address", label: "Email Address", id: "0" },
  { value: "Phone Number", label: "Phone Number", id: "1" },
  { value: "Mobile Advertisor Id", label: "Mobile Advertisor Id", id: "2" },
  { value: "First Name", label: "First Name", id: "3" },
  { value: "Sur Name", label: "Sur Name", id: "4" },
  { value: "Zip/Postal Code", label: "Zip/Postal Code", id: "5" },
  { value: "City", label: "City", id: "6" },
  { value: "Country/Region", label: "Country/Region", id: "7" },
  { value: "Country", label: "Country", id: "8" },
];

// export const CITIES = [
//   "Achalpur",
//   "Achhnera",
//   "Adalaj",
//   "Adilabad",
//   "Adityapur",
//   "Adoni",
//   "Adoor",
//   "Adra",
//   "Adyar",
//   "Afzalpur",
//   "Agartala",
//   "Agra",
//   "Ahmedabad",
//   "Ahmednagar",
//   "Aizawl",
//   "Ajmer",
//   "Akola",
//   "Akot",
//   "Alappuzha",
//   "Aligarh",
//   "AlipurdUrban Agglomerationr",
//   "Alirajpur",
//   "Allahabad",
//   "Alwar",
//   "Amalapuram",
//   "Amalner",
//   "Ambejogai",
//   "Ambikapur",
//   "Amravati",
//   "Amreli",
//   "Amritsar",
//   "Amroha",
//   "Anakapalle",
//   "Anand",
//   "Anantapur",
//   "Anantnag",
//   "Anjangaon",
//   "Anjar",
//   "Ankleshwar",
//   "Arakkonam",
//   "Arambagh",
//   "Araria",
//   "Arrah",
//   "Arsikere",
//   "Aruppukkottai",
//   "Arvi",
//   "Arwal",
//   "Asansol",
//   "Asarganj",
//   "Ashok Nagar",
//   "Athni",
//   "Attingal",
//   "Aurangabad",
//   "Aurangabad",
//   "Azamgarh",
//   "Bagaha",
//   "Bageshwar",
//   "Bahadurgarh",
//   "Baharampur",
//   "Bahraich",
//   "Balaghat",
//   "Balangir",
//   "Baleshwar Town",
//   "Ballari",
//   "Balurghat",
//   "Bankura",
//   "Bapatla",
//   "Baramula",
//   "Barbil",
//   "Bargarh",
//   "Barh",
//   "Baripada Town",
//   "Barmer",
//   "Barnala",
//   "Barpeta",
//   "Batala",
//   "Bathinda",
//   "Begusarai",
//   "Belagavi",
//   "Bellampalle",
//   "Belonia",
//   "Bengaluru",
//   "Bettiah",
//   "BhabUrban Agglomeration",
//   "Bhadrachalam",
//   "Bhadrak",
//   "Bhagalpur",
//   "Bhainsa",
//   "Bharatpur",
//   "Bharuch",
//   "Bhatapara",
//   "Bhavnagar",
//   "Bhawanipatna",
//   "Bheemunipatnam",
//   "Bhilai Nagar",
//   "Bhilwara",
//   "Bhimavaram",
//   "Bhiwandi",
//   "Bhiwani",
//   "Bhongir",
//   "Bhopal",
//   "Bhubaneswar",
//   "Bhuj",
//   "Bikaner",
//   "Bilaspur",
//   "Bobbili",
//   "Bodhan",
//   "Bokaro Steel City",
//   "Bongaigaon City",
//   "Brahmapur",
//   "Buxar",
//   "Byasanagar",
//   "Chaibasa",
//   "Chalakudy",
//   "Chandausi",
//   "Chandigarh",
//   "Changanassery",
//   "Charkhi Dadri",
//   "Chatra",
//   "Chennai",
//   "Cherthala",
//   "Chhapra",
//   "Chhapra",
//   "Chikkamagaluru",
//   "Chilakaluripet",
//   "Chirala",
//   "Chirkunda",
//   "Chirmiri",
//   "Chittoor",
//   "Chittur-Thathamangalam",
//   "Coimbatore",
//   "Cuttack",
//   "Dalli-Rajhara",
//   "Darbhanga",
//   "Darjiling",
//   "Davanagere",
//   "Deesa",
//   "Dehradun",
//   "Dehri-on-Sone",
//   "Delhi",
//   "Deoghar",
//   "Dhamtari",
//   "Dhanbad",
//   "Dharmanagar",
//   "Dharmavaram",
//   "Dhenkanal",
//   "Dhoraji",
//   "Dhubri",
//   "Dhule",
//   "Dhuri",
//   "Dibrugarh",
//   "Dimapur",
//   "Diphu",
//   "Dumka",
//   "Dumraon",
//   "Durg",
//   "Eluru",
//   "English Bazar",
//   "Erode",
//   "Etawah",
//   "Faridabad",
//   "Faridkot",
//   "Farooqnagar",
//   "Fatehabad",
//   "Fatehpur Sikri",
//   "Fazilka",
//   "Firozabad",
//   "Firozpur Cantt.",
//   "Firozpur",
//   "Forbesganj",
//   "Gadwal",
//   "Gandhinagar",
//   "Gangarampur",
//   "Ganjbasoda",
//   "Gaya",
//   "Giridih",
//   "Goalpara",
//   "Gobichettipalayam",
//   "Gobindgarh",
//   "Godhra",
//   "Gohana",
//   "Gokak",
//   "Gooty",
//   "Gopalganj",
//   "Gudivada",
//   "Gudur",
//   "Gumia",
//   "Guntakal",
//   "Guntur",
//   "Gurdaspur",
//   "Gurgaon",
//   "Guruvayoor",
//   "Guwahati",
//   "Gwalior",
//   "Habra",
//   "Hajipur",
//   "Haldwani-cum-Kathgodam",
//   "Hansi",
//   "Hapur",
//   "Hardoi ",
//   "Hardwar",
//   "Hazaribag",
//   "Hindupur",
//   "Hisar",
//   "Hoshiarpur",
//   "Hubli-Dharwad",
//   "Hugli-Chinsurah",
//   "Hyderabad",
//   "Ichalkaranji",
//   "Imphal",
//   "Indore",
//   "Itarsi",
//   "Jabalpur",
//   "Jagdalpur",
//   "Jaggaiahpet",
//   "Jagraon",
//   "Jagtial",
//   "Jaipur",
//   "Jalandhar Cantt.",
//   "Jalandhar",
//   "Jalpaiguri",
//   "Jamalpur",
//   "Jammalamadugu",
//   "Jammu",
//   "Jamnagar",
//   "Jamshedpur",
//   "Jamui",
//   "Jangaon",
//   "Jatani",
//   "Jehanabad",
//   "Jhansi",
//   "Jhargram",
//   "Jharsuguda",
//   "Jhumri Tilaiya",
//   "Jind",
//   "Jodhpur",
//   "Jorhat",
//   "Kadapa",
//   "Kadi",
//   "Kadiri",
//   "Kagaznagar",
//   "Kailasahar",
//   "Kaithal",
//   "Kakinada",
//   "Kalimpong",
//   "Kalpi",
//   "Kalyan-Dombivali",
//   "Kamareddy",
//   "Kancheepuram",
//   "Kandukur",
//   "Kanhangad",
//   "Kannur",
//   "Kanpur",
//   "Kapadvanj",
//   "Kapurthala",
//   "Karaikal",
//   "Karimganj",
//   "Karimnagar",
//   "Karjat",
//   "Karnal",
//   "Karur",
//   "Karwar",
//   "Kasaragod",
//   "Kashipur",
//   "KathUrban Agglomeration",
//   "Katihar",
//   "Kavali",
//   "Kayamkulam",
//   "Kendrapara",
//   "Kendujhar",
//   "Keshod",
//   "Khair",
//   "Khambhat",
//   "Khammam",
//   "Khanna",
//   "Kharagpur",
//   "Kharar",
//   "Khowai",
//   "Kishanganj",
//   "Kochi",
//   "Kodungallur",
//   "Kohima",
//   "Kolar",
//   "Kolkata",
//   "Kollam",
//   "Koratla",
//   "Korba",
//   "Kot Kapura",
//   "Kota",
//   "Kothagudem",
//   "Kottayam",
//   "Kovvur",
//   "Koyilandy",
//   "Kozhikode",
//   "Kunnamkulam",
//   "Kurnool",
//   "Kyathampalle",
//   "Lachhmangarh",
//   "Ladnu",
//   "Ladwa",
//   "Lahar",
//   "Laharpur",
//   "Lakheri",
//   "Lakhimpur",
//   "Lakhisarai",
//   "Lakshmeshwar",
//   "Lal Gopalganj Nindaura",
//   "Lalganj",
//   "Lalganj",
//   "Lalgudi",
//   "Lalitpur",
//   "Lalsot",
//   "Lanka",
//   "Lar",
//   "Lathi",
//   "Latur",
//   "Lilong",
//   "Limbdi",
//   "Lingsugur",
//   "Loha",
//   "Lohardaga",
//   "Lonar",
//   "Lonavla",
//   "Longowal",
//   "Loni",
//   "Losal",
//   "Lucknow",
//   "Ludhiana",
//   "Lumding",
//   "Lunawada",
//   "Lunglei",
//   "Macherla",
//   "Machilipatnam",
//   "Madanapalle",
//   "Maddur",
//   "Madhepura",
//   "Madhubani",
//   "Madhugiri",
//   "Madhupur",
//   "Madikeri",
//   "Madurai",
//   "Magadi",
//   "Mahad",
//   "Mahalingapura",
//   "Maharajganj",
//   "Maharajpur",
//   "Mahasamund",
//   "Mahbubnagar",
//   "Mahe",
//   "Mahemdabad",
//   "Mahendragarh",
//   "Mahesana",
//   "Mahidpur",
//   "Mahnar Bazar",
//   "Mahuva",
//   "Maihar",
//   "Mainaguri",
//   "Makhdumpur",
//   "Makrana",
//   "Malaj Khand",
//   "Malappuram",
//   "Malavalli",
//   "Malda",
//   "Malegaon",
//   "Malerkotla",
//   "Malkangiri",
//   "Malkapur",
//   "Malout",
//   "Malpura",
//   "Malur",
//   "Manachanallur",
//   "Manasa",
//   "Manavadar",
//   "Manawar",
//   "Mancherial",
//   "Mandalgarh",
//   "Mandamarri",
//   "Mandapeta",
//   "Mandawa",
//   "Mandi Dabwali",
//   "Mandi",
//   "Mandideep",
//   "Mandla",
//   "Mandsaur",
//   "Mandvi",
//   "Mandya",
//   "Manendragarh",
//   "Maner",
//   "Mangaldoi",
//   "Mangaluru",
//   "Mangalvedhe",
//   "Manglaur",
//   "Mangrol",
//   "Mangrol",
//   "Mangrulpir",
//   "Manihari",
//   "Manjlegaon",
//   "Mankachar",
//   "Manmad",
//   "Mansa",
//   "Mansa",
//   "Manuguru",
//   "Manvi",
//   "Manwath",
//   "Mapusa",
//   "Margao",
//   "Margherita",
//   "Marhaura",
//   "Mariani",
//   "Marigaon",
//   "Markapur",
//   "Marmagao",
//   "Masaurhi",
//   "Mathabhanga",
//   "Mathura",
//   "Mattannur",
//   "Mauganj",
//   "Mavelikkara",
//   "Mavoor",
//   "Mayang Imphal",
//   "Medak",
//   "Medininagar (Daltonganj)",
//   "Medinipur",
//   "Meerut",
//   "Mehkar",
//   "Memari",
//   "Merta City",
//   "Mhaswad",
//   "Mhow Cantonment",
//   "Mhowgaon",
//   "Mihijam",
//   "Mira-Bhayandar",
//   "Mirganj",
//   "Miryalaguda",
//   "Modasa",
//   "Modinagar",
//   "Moga",
//   "Mohali",
//   "Mokameh",
//   "Mokokchung",
//   "Monoharpur",
//   "Moradabad",
//   "Morena",
//   "Morinda, India",
//   "Morshi",
//   "Morvi",
//   "Motihari",
//   "Motipur",
//   "Mount Abu",
//   "Mudabidri",
//   "Mudalagi",
//   "Muddebihal",
//   "Mudhol",
//   "Mukerian",
//   "Mukhed",
//   "Muktsar",
//   "Mul",
//   "Mulbagal",
//   "Multai",
//   "Mumbai",
//   "Mundargi",
//   "Mundi",
//   "Mungeli",
//   "Munger",
//   "Murliganj",
//   "Murshidabad",
//   "Murtijapur",
//   "Murwara (Katni)",
//   "Musabani",
//   "Mussoorie",
//   "Muvattupuzha",
//   "Muzaffarpur",
//   "Mysore",
//   "Nabadwip",
//   "Nabarangapur",
//   "Nabha",
//   "Nadbai",
//   "Nadiad",
//   "Nagaon",
//   "Nagapattinam",
//   "Nagar",
//   "Nagari",
//   "Nagarkurnool",
//   "Nagaur",
//   "Nagda",
//   "Nagercoil",
//   "Nagina",
//   "Nagla",
//   "Nagpur",
//   "Nahan",
//   "Naharlagun",
//   "Naidupet",
//   "Naihati",
//   "Naila Janjgir",
//   "Nainital",
//   "Nainpur",
//   "Najibabad",
//   "Nakodar",
//   "Nakur",
//   "Nalbari",
//   "Namagiripettai",
//   "Namakkal",
//   "Nanded-Waghala",
//   "Nandgaon",
//   "Nandivaram-Guduvancheri",
//   "Nandura",
//   "Nandurbar",
//   "Nandyal",
//   "Nangal",
//   "Nanjangud",
//   "Nanjikottai",
//   "Nanpara",
//   "Narasapuram",
//   "Narasaraopet",
//   "Naraura",
//   "Narayanpet",
//   "Nargund",
//   "Narkatiaganj",
//   "Narkhed",
//   "Narnaul",
//   "Narsinghgarh",
//   "Narsinghgarh",
//   "Narsipatnam",
//   "Narwana",
//   "Nashik",
//   "Nasirabad",
//   "Natham",
//   "Nathdwara",
//   "Naugachhia",
//   "Naugawan Sadat",
//   "Nautanwa",
//   "Navalgund",
//   "Navsari",
//   "Nawabganj",
//   "Nawada",
//   "Nawanshahr",
//   "Nawapur",
//   "Nedumangad",
//   "Neem-Ka-Thana",
//   "Neemuch",
//   "Nehtaur",
//   "Nelamangala",
//   "Nellikuppam",
//   "Nellore",
//   "Nepanagar",
//   "New Delhi",
//   "Neyveli (TS)",
//   "Neyyattinkara",
//   "Nidadavole",
//   "Nilambur",
//   "Nilanga",
//   "Nimbahera",
//   "Nirmal",
//   "Niwai",
//   "Niwari",
//   "Nizamabad",
//   "Nohar",
//   "Noida",
//   "Nokha",
//   "Nokha",
//   "Nongstoin",
//   "Noorpur",
//   "North Lakhimpur",
//   "Nowgong",
//   "Nowrozabad (Khodargama)",
//   "Nuzvid",
//   "O' Valley",
//   "Obra",
//   "Oddanchatram",
//   "Ongole",
//   "Orai",
//   "Osmanabad",
//   "Ottappalam",
//   "Ozar",
//   "P.N.Patti",
//   "Pachora",
//   "Pachore",
//   "Pacode",
//   "Padmanabhapuram",
//   "Padra",
//   "Padrauna",
//   "Paithan",
//   "Pakaur",
//   "Palacole",
//   "Palai",
//   "Palakkad",
//   "Palampur",
//   "Palani",
//   "Palanpur",
//   "Palasa Kasibugga",
//   "Palghar",
//   "Pali",
//   "Pali",
//   "Palia Kalan",
//   "Palitana",
//   "Palladam",
//   "Pallapatti",
//   "Pallikonda",
//   "Palwal",
//   "Palwancha",
//   "Panagar",
//   "Panagudi",
//   "Panaji",
//   "Panamattom",
//   "Panchkula",
//   "Panchla",
//   "Pandharkaoda",
//   "Pandharpur",
//   "Pandhurna",
//   "PandUrban Agglomeration",
//   "Panipat",
//   "Panna",
//   "Panniyannur",
//   "Panruti",
//   "Panvel",
//   "Pappinisseri",
//   "Paradip",
//   "Paramakudi",
//   "Parangipettai",
//   "Parasi",
//   "Paravoor",
//   "Parbhani",
//   "Pardi",
//   "Parlakhemundi",
//   "Parli",
//   "Partur",
//   "Parvathipuram",
//   "Pasan",
//   "Paschim Punropara",
//   "Pasighat",
//   "Patan",
//   "Pathanamthitta",
//   "Pathankot",
//   "Pathardi",
//   "Pathri",
//   "Patiala",
//   "Patna",
//   "Patratu",
//   "Pattamundai",
//   "Patti",
//   "Pattran",
//   "Pattukkottai",
//   "Patur",
//   "Pauni",
//   "Pauri",
//   "Pavagada",
//   "Pedana",
//   "Peddapuram",
//   "Pehowa",
//   "Pen",
//   "Perambalur",
//   "Peravurani",
//   "Peringathur",
//   "Perinthalmanna",
//   "Periyakulam",
//   "Periyasemur",
//   "Pernampattu",
//   "Perumbavoor",
//   "Petlad",
//   "Phagwara",
//   "Phalodi",
//   "Phaltan",
//   "Phillaur",
//   "Phulabani",
//   "Phulera",
//   "Phulpur",
//   "Phusro",
//   "Pihani",
//   "Pilani",
//   "Pilibanga",
//   "Pilibhit",
//   "Pilkhuwa",
//   "Pindwara",
//   "Pinjore",
//   "Pipar City",
//   "Pipariya",
//   "Piriyapatna",
//   "Piro",
//   "Pithampur",
//   "Pithapuram",
//   "Pithoragarh",
//   "Pollachi",
//   "Polur",
//   "Pondicherry",
//   "Ponnani",
//   "Ponneri",
//   "Ponnur",
//   "Porbandar",
//   "Porsa",
//   "Port Blair",
//   "Powayan",
//   "Prantij",
//   "Pratapgarh",
//   "Pratapgarh",
//   "Prithvipur",
//   "Proddatur",
//   "Pudukkottai",
//   "Pudupattinam",
//   "Pukhrayan",
//   "Pulgaon",
//   "Puliyankudi",
//   "Punalur",
//   "Punch",
//   "Pune",
//   "Punganur",
//   "Punjaipugalur",
//   "Puranpur",
//   "Puri",
//   "Purna",
//   "Purnia",
//   "PurqUrban Agglomerationzi",
//   "Purulia",
//   "Purwa",
//   "Pusad",
//   "Puthuppally",
//   "Puttur",
//   "Puttur",
//   "Qadian",
//   "Raayachuru",
//   "Rabkavi Banhatti",
//   "Radhanpur",
//   "Rae Bareli",
//   "Rafiganj",
//   "Raghogarh-Vijaypur",
//   "Raghunathganj",
//   "Raghunathpur",
//   "Rahatgarh",
//   "Rahuri",
//   "Raiganj",
//   "Raigarh",
//   "Raikot",
//   "Raipur",
//   "Rairangpur",
//   "Raisen",
//   "Raisinghnagar",
//   "Rajagangapur",
//   "Rajahmundry",
//   "Rajakhera",
//   "Rajaldesar",
//   "Rajam",
//   "Rajampet",
//   "Rajapalayam",
//   "Rajauri",
//   "Rajgarh (Alwar)",
//   "Rajgarh (Churu)",
//   "Rajgarh",
//   "Rajgir",
//   "Rajkot",
//   "Rajnandgaon",
//   "Rajpipla",
//   "Rajpura",
//   "Rajsamand",
//   "Rajula",
//   "Rajura",
//   "Ramachandrapuram",
//   "Ramagundam",
//   "Ramanagaram",
//   "Ramanathapuram",
//   "Ramdurg",
//   "Rameshwaram",
//   "Ramganj Mandi",
//   "Ramgarh",
//   "Ramnagar",
//   "Ramnagar",
//   "Ramngarh",
//   "Rampur Maniharan",
//   "Rampur",
//   "Rampura Phul",
//   "Rampurhat",
//   "Ramtek",
//   "Ranaghat",
//   "Ranavav",
//   "Ranchi",
//   "Ranebennuru",
//   "Rangia",
//   "Rania",
//   "Ranibennur",
//   "Ranipet",
//   "Rapar",
//   "Rasipuram",
//   "Rasra",
//   "Ratangarh",
//   "Rath",
//   "Ratia",
//   "Ratlam",
//   "Ratnagiri",
//   "Rau",
//   "Raurkela",
//   "Raver",
//   "Rawatbhata",
//   "Rawatsar",
//   "Raxaul Bazar",
//   "Rayachoti",
//   "Rayadurg",
//   "Rayagada",
//   "Reengus",
//   "Rehli",
//   "Renigunta",
//   "Renukoot",
//   "Reoti",
//   "Repalle",
//   "Revelganj",
//   "Rewa",
//   "Rewari",
//   "Rishikesh",
//   "Risod",
//   "Robertsganj",
//   "Robertson Pet",
//   "Rohtak",
//   "Ron",
//   "Roorkee",
//   "Rosera",
//   "Rudauli",
//   "Rudrapur",
//   "Rudrapur",
//   "Rupnagar",
//   "Sabalgarh",
//   "Sadabad",
//   "Sadalagi",
//   "Sadasivpet",
//   "Sadri",
//   "Sadulpur",
//   "Sadulshahar",
//   "Safidon",
//   "Safipur",
//   "Sagar",
//   "Sagara",
//   "Sagwara",
//   "Saharanpur",
//   "Saharsa",
//   "Sahaspur",
//   "Sahaswan",
//   "Sahawar",
//   "Sahibganj",
//   "Sahjanwa",
//   "Saidpur",
//   "Saiha",
//   "Sailu",
//   "Sainthia",
//   "Sakaleshapura",
//   "Sakti",
//   "Salaya",
//   "Salem",
//   "Salur",
//   "Samalkha",
//   "Samalkot",
//   "Samana",
//   "Samastipur",
//   "Sambalpur",
//   "Sambhal",
//   "Sambhar",
//   "Samdhan",
//   "Samthar",
//   "Sanand",
//   "Sanawad",
//   "Sanchore",
//   "Sandi",
//   "Sandila",
//   "Sanduru",
//   "Sangamner",
//   "Sangareddy",
//   "Sangaria",
//   "Sangli",
//   "Sangole",
//   "Sangrur",
//   "Sankarankovil",
//   "Sankari",
//   "Sankeshwara",
//   "Santipur",
//   "Sarangpur",
//   "Sardarshahar",
//   "Sardhana",
//   "Sarni",
//   "Sarsod",
//   "Sasaram",
//   "Sasvad",
//   "Satana",
//   "Satara",
//   "Sathyamangalam",
//   "Satna",
//   "Sattenapalle",
//   "Sattur",
//   "Saunda",
//   "Saundatti-Yellamma",
//   "Sausar",
//   "Savanur",
//   "Savarkundla",
//   "Savner",
//   "Sawai Madhopur",
//   "Sawantwadi",
//   "Sedam",
//   "Sehore",
//   "Sendhwa",
//   "Seohara",
//   "Seoni",
//   "Seoni-Malwa",
//   "Shahabad",
//   "Shahabad, Hardoi",
//   "Shahabad, Rampur",
//   "Shahade",
//   "Shahbad",
//   "Shahdol",
//   "Shahganj",
//   "Shahjahanpur",
//   "Shahpur",
//   "Shahpura",
//   "Shahpura",
//   "Shajapur",
//   "Shamgarh",
//   "Shamli",
//   "Shamsabad, Agra",
//   "Shamsabad, Farrukhabad",
//   "Shegaon",
//   "Sheikhpura",
//   "Shendurjana",
//   "Shenkottai",
//   "Sheoganj",
//   "Sheohar",
//   "Sheopur",
//   "Sherghati",
//   "Sherkot",
//   "Shiggaon",
//   "Shikaripur",
//   "Shikarpur, Bulandshahr",
//   "Shikohabad",
//   "Shillong",
//   "Shimla",
//   "Shirdi",
//   "Shirpur-Warwade",
//   "Shirur",
//   "Shishgarh",
//   "Shivamogga",
//   "Shivpuri",
//   "Sholavandan",
//   "Sholingur",
//   "Shoranur",
//   "Shrigonda",
//   "Shrirampur",
//   "Shrirangapattana",
//   "Shujalpur",
//   "Siana",
//   "Sibsagar",
//   "Siddipet",
//   "Sidhi",
//   "Sidhpur",
//   "Sidlaghatta",
//   "Sihor",
//   "Sihora",
//   "Sikanderpur",
//   "Sikandra Rao",
//   "Sikandrabad",
//   "Sikar",
//   "Silao",
//   "Silapathar",
//   "Silchar",
//   "Siliguri",
//   "Sillod",
//   "Silvassa",
//   "Simdega",
//   "Sindagi",
//   "Sindhagi",
//   "Sindhnur",
//   "Singrauli",
//   "Sinnar",
//   "Sira",
//   "Sircilla",
//   "Sirhind Fatehgarh Sahib",
//   "Sirkali",
//   "Sirohi",
//   "Sironj",
//   "Sirsa",
//   "Sirsaganj",
//   "Sirsi",
//   "Sirsi",
//   "Siruguppa",
//   "Sitamarhi",
//   "Sitapur",
//   "Sitarganj",
//   "Sivaganga",
//   "Sivagiri",
//   "Sivakasi",
//   "Siwan",
//   "Sohagpur",
//   "Sohna",
//   "Sojat",
//   "Solan",
//   "Solapur",
//   "Sonamukhi",
//   "Sonepur",
//   "Songadh",
//   "Sonipat",
//   "Sopore",
//   "Soro",
//   "Soron",
//   "Soyagaon",
//   "Sri Madhopur",
//   "Srikakulam",
//   "Srikalahasti",
//   "Srinagar",
//   "Srinagar",
//   "Srinivaspur",
//   "Srirampore",
//   "Srisailam Project (Right Flank Colony) Township",
//   "Srivilliputhur",
//   "Sugauli",
//   "Sujangarh",
//   "Sujanpur",
//   "Sullurpeta",
//   "Sultanganj",
//   "Sultanpur",
//   "Sumerpur",
//   "Sumerpur",
//   "Sunabeda",
//   "Sunam",
//   "Sundargarh",
//   "Sundarnagar",
//   "Supaul",
//   "Surandai",
//   "Surapura",
//   "Surat",
//   "Suratgarh",
//   "SUrban Agglomerationr",
//   "Suri",
//   "Suriyampalayam",
//   "Suryapet",
//   "Tadepalligudem",
//   "Tadpatri",
//   "Takhatgarh",
//   "Taki",
//   "Talaja",
//   "Talcher",
//   "Talegaon Dabhade",
//   "Talikota",
//   "Taliparamba",
//   "Talode",
//   "Talwara",
//   "Tamluk",
//   "Tanda",
//   "Tandur",
//   "Tanuku",
//   "Tarakeswar",
//   "Tarana",
//   "Taranagar",
//   "Taraori",
//   "Tarbha",
//   "Tarikere",
//   "Tarn Taran",
//   "Tasgaon",
//   "Tehri",
//   "Tekkalakote",
//   "Tenali",
//   "Tenkasi",
//   "Tenu dam-cum-Kathhara",
//   "Terdal",
//   "Tezpur",
//   "Thakurdwara",
//   "Thammampatti",
//   "Thana Bhawan",
//   "Thane",
//   "Thanesar",
//   "Thangadh",
//   "Thanjavur",
//   "Tharad",
//   "Tharamangalam",
//   "Tharangambadi",
//   "Theni Allinagaram",
//   "Thirumangalam",
//   "Thirupuvanam",
//   "Thiruthuraipoondi",
//   "Thiruvalla",
//   "Thiruvallur",
//   "Thiruvananthapuram",
//   "Thiruvarur",
//   "Thodupuzha",
//   "Thoubal",
//   "Thrissur",
//   "Thuraiyur",
//   "Tikamgarh",
//   "Tilda Newra",
//   "Tilhar",
//   "Tindivanam",
//   "Tinsukia",
//   "Tiptur",
//   "Tirora",
//   "Tiruchendur",
//   "Tiruchengode",
//   "Tiruchirappalli",
//   "Tirukalukundram",
//   "Tirukkoyilur",
//   "Tirunelveli",
//   "Tirupathur",
//   "Tirupathur",
//   "Tirupati",
//   "Tiruppur",
//   "Tirur",
//   "Tiruttani",
//   "Tiruvannamalai",
//   "Tiruvethipuram",
//   "Tiruvuru",
//   "Tirwaganj",
//   "Titlagarh",
//   "Tittakudi",
//   "Todabhim",
//   "Todaraisingh",
//   "Tohana",
//   "Tonk",
//   "Tuensang",
//   "Tuljapur",
//   "Tulsipur",
//   "Tumkur",
//   "Tumsar",
//   "Tundla",
//   "Tuni",
//   "Tura",
//   "Uchgaon",
//   "Udaipur",
//   "Udaipur",
//   "Udaipurwati",
//   "Udgir",
//   "Udhagamandalam",
//   "Udhampur",
//   "Udumalaipettai",
//   "Udupi",
//   "Ujhani",
//   "Ujjain",
//   "Umarga",
//   "Umaria",
//   "Umarkhed",
//   "Umbergaon",
//   "Umred",
//   "Umreth",
//   "Una",
//   "Unjha",
//   "Unnamalaikadai",
//   "Unnao",
//   "Upleta",
//   "Uran Islampur",
//   "Uran",
//   "Uravakonda",
//   "Urmar Tanda",
//   "Usilampatti",
//   "Uthamapalayam",
//   "Uthiramerur",
//   "Utraula",
//   "Vadakkuvalliyur",
//   "Vadalur",
//   "Vadgaon Kasba",
//   "Vadipatti",
//   "Vadnagar",
//   "Vadodara",
//   "Vaijapur",
//   "Vaikom",
//   "Valparai",
//   "Valsad",
//   "Vandavasi",
//   "Vaniyambadi",
//   "Vapi",
//   "Vapi",
//   "Varanasi",
//   "Varkala",
//   "Vasai-Virar",
//   "Vatakara",
//   "Vedaranyam",
//   "Vellakoil",
//   "Vellore",
//   "Venkatagiri",
//   "Veraval",
//   "Vidisha",
//   "Vijainagar, Ajmer",
//   "Vijapur",
//   "Vijayapura",
//   "Vijayawada",
//   "Vijaypur",
//   "Vikarabad",
//   "Vikramasingapuram",
//   "Viluppuram",
//   "Vinukonda",
//   "Viramgam",
//   "Virudhachalam",
//   "Virudhunagar",
//   "Visakhapatnam",
//   "Visnagar",
//   "Viswanatham",
//   "Vita",
//   "Vizianagaram",
//   "Vrindavan",
//   "Vyara",
//   "Wadgaon Road",
//   "Wadhwan",
//   "Wadi",
//   "Wai",
//   "Wanaparthy",
//   "Wani",
//   "Wankaner",
//   "Wara Seoni",
//   "Warangal",
//   "Wardha",
//   "Warhapur",
//   "Warisaliganj",
//   "Warora",
//   "Warud",
//   "Washim",
//   "Wokha",
//   "Yadgir",
//   "Yamunanagar",
//   "Yanam",
//   "Yavatmal",
//   "Yawal",
//   "Yellandu",
//   "Yemmiganur",
//   "Yerraguntla",
//   "Yevla",
//   "Zaidpur",
//   "Zamania",
//   "Zira",
//   "Zirakpur",
//   "Zunheboto",
// ];

const RegionOptions = [
  { value: "All India", label: "All India" },
  { value: "North India", label: "North India" },
  { value: "South India", label: "South India" },
  { value: "East India", label: "East India" },
  { value: "West India", label: "West India" },
  { value: "Global", label: "Global" },
  { value: "North-East India", label: "North-East India" },
];

export const region = RegionOptions.map((e, i) => ({
  value: e.value,
  label: e.label,
}));
export const demographics = [
  { value: "Student", label: "Student" },
  { value: "Employee", label: "Employee" },
  { value: "SelfEmployed", label: "Self-employed" },
  { value: "HomeMaker", label: "Home Maker" },
];
export const gender = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "Unisex", label: "Unisex" },
];

export const CAMERA_TABS = {
  CAMERA_PERSPECTIVE: "perspective",
  CAMERA_FILTERS: "filters",
  SHUTTERS_SPEEDS: "shutter",
  LIGHTING_OPTIONS: "lighting",
};

export const BRAND_TABS = {
  CREATIVE: "creative",
  CAMPAIGN: "camaign",
  BRANDING: "branding",
  MEDIA: "media",
  PROMPT: "prompt",
};

export const CTR_PREDICTION = {
  BRANDING: "branding",
  CAMPAIGN: "camaign",
  UPLOAD: "upload",
};

export const BRAND_TABS_Two = {
  PRODUCTNAME: "name",
  PRODUCTIMAGE: "image",
  IMAGEBACKDROPS: "backdrops",
};

export const BRAND_TABS_Three = {
  CREATIVE: "creative",
  CAMPAIGN: "camaign",
  CONTEXT: "context",
  BRANDING: "branding",
  SETTINGS: "settings",
  PAINTING: "painting",
  BACKGROUND: "background",
  MEDIA: "media",
};

export const IMAGE_TO_VIDEO_TABS = {
  IMAGE: "image",
  STYLE: "style",
  MOTION: "motion",
  LENGTH: "length",
  FOCUSPOINT: "focuspoint",
  PAINTING: "painting",
};

export const SONIC_AI_TABS = {
  MUSICGENRE: "musicgenre",
  MUSICUPLOAD: "musicupload",
};

export const VIRTUAL_TRYON_TABS = {
  FASHION: "UseFashionKit",
  PHOTOSHOOT: "PhotoshootSelection",
  BACKGROUND: "BackgroundOptions",
};

export const style = [
  { value: "Illustration", label: "Illustration" },
  { value: "Artistic", label: "Artistic" },
  { value: "Photorealistic", label: "Photorealistic" },
  { value: "Cinematic", label: "Cinematic" },
  { value: "Digital Media", label: "Digital Media" },
  { value: "3-D Art", label: "3-D Art" },
];

export const IllustrationOptions = [
  { value: "Monochromatic", label: "Monochromatic" },
  { value: "Colors", label: "Colors" },
  { value: "Digital Media", label: "Digital Media" },
  { value: "Cartoons", label: "Cartoons" },
];
export const MonochromaticOptions = [
  { value: "Pencil Art", label: "Pencil Art" },
  { value: "Steel Art", label: "Steel Art" },
  { value: "Ball Point Pen", label: "Ball Point pen" },
  { value: "Charcoal Sketch", label: "Charcoal Sketch" },
];
export const ColorOptions = [
  { value: "Crayon", label: "Crayon" },
  { value: "Acrylic on Canvas", label: "Acrylic on Canvas" },
  { value: "Watercolor", label: "Watercolor" },
  { value: "Color Pencil", label: "Color Pencil" },
];
export const DigitalMediaOptions = [
  { value: "Photo Collage", label: "Photo Collage" },
  { value: "Vector Art", label: "Vector Art" },
  { value: "Digital Painting", label: "Digital Painting" },
];

export const CartoonOptions = [
  { value: "Comic Book", label: "Comic Book" },
  { value: "Anime", label: "Anime" },
  { value: "Pixel Art", label: "Pixel Art" },
  { value: "Vintage", label: "Vintage" },
];

export const ArtisticOptions = [
  { value: "Aesthetic Style", label: "Aesthetic Style" },
  { value: "Regional Style", label: "Regional Style" },
  { value: "Time Period Based", label: "Time Period Based" },
  { value: "Art movements", label: "Art Movements" },
];
export const AestheticStyleOptions = [
  { value: "Renaissance", label: "Renaissance" },
  { value: "Baroque", label: "Baroque" },
  { value: "Impressionism", label: "Impressionism" },
];
export const RegionalOptions = [
  { value: "Japanese Woodblock Print", label: "Japanese Woodblock Print" },
  { value: "Mexican Muralism", label: "Mexican Muralism" },
  { value: "Italian Baroque", label: "Italian Baroque" },
];
export const TimePeriodOptions = [
  { value: "Ancient", label: "Ancient" },
  { value: "Medieval Art", label: "Medieval Art" },
  { value: "Contemporary", label: "Contemporary" },
  { value: "Modern Art", label: "Modern Art" },
];
export const ArtMovementOptions = [
  { value: "Cubism", label: "Cubism" },
  { value: "Art Nouveau", label: "Anime" },
  { value: "Futurism", label: "Futurism" },
  { value: "Punk", label: "Punk" },
];

export const cinematicOptions = [
  { value: "Vintage/Cine Film", label: "Vintage/Cinefilm" },
  { value: "Documentary Style", label: "Documentary Style" },
  { value: "Cinematic Portraiture", label: "Cinematic Portraiture" },
];
export const vintageCinefilmOptions = [
  { value: "Classic Hollywood", label: "Classic Hollywood" },
  { value: "Silent Film Era", label: "Silent Film Era" },
  { value: "Golden Age of Cinema", label: "Golden Age of Cinema" },
  { value: "Film Noir Aesthetics", label: "Film Noir Aesthetics" },
];

export const documentaryStyleOptions = [
  { value: "Cinéma vérité", label: "Cinéma vérité" },
  { value: "Fly on the Wall", label: "Fly on the Wall" },
  { value: "Observational Documentary", label: "Observational Documentary" },
];
export const cinematicPortraitureOptions = [
  { value: "Dramatic Lighting", label: "Dramatic Lighting" },
  { value: "Fantasy Portraits", label: "Fantasy Portraits" },
  { value: "Science Fiction/Futuristic", label: "Science Fiction/Futuristic" },
];

export const digitalMediaOptions = [
  { value: "Photo Manipulation", label: "Photo Manipulation" },
  { value: "Digital Mixed Media", label: "Digital Mixed Media" },
  { value: "Digital Illustration", label: "Digital Illustration" },
];
export const photoManipulationOptions = [
  { value: "Fantasy Photo Manipulation", label: "Fantasy Photo Manipulation" },
  { value: "Surreal Photo Editing", label: "Surreal Photo Editing" },
  { value: "Double Exposure Effects", label: "Double Exposure Effects" },
  { value: "Photo Compositing", label: "Photo Compositing" },
];

export const digitalMixedMediaOptions = [
  { value: "Assemblage Art", label: "Assemblage Art" },
  { value: "Digital Embroidery", label: "Digital Embroidery" },
  { value: "Textured Digital Art", label: "Textured Digital Art" },
  { value: "Layered Digital Media", label: "Layered Digital Media" },
  { value: "Photo collage", label: "Photo collage" },
];

export const digitalIllustrationOptions = [
  { value: "Vector Art", label: "Vector Art" },
  { value: "Screen Printing", label: "Screen Printing" },
  { value: "Sticker Illustration", label: "Sticker Illustration" },
  { value: "Digital Watercolor", label: "Digital Watercolor" },
];

export const ThreeDArtOptions = [
  { value: "Items for Human Body", label: "Items for Human Body" },
  { value: "3D Places and Spaces", label: "3D Places and Spaces" },
  {
    value: "3D Animations and Characters",
    label: "3D Animations and Characters",
  },
];
export const ThreeDPlacesAndSpacesOptions = [
  { value: "Architecture", label: "Architecture" },
  {
    value: "Domestic interiors, home design",
    label: "Domestic interiors, home design",
  },
  { value: "Gardens, landscaping", label: "Gardens, landscaping" },
  { value: "Crafts and Models", label: "Crafts and Models" },
];

export const ItemsForHumanBodyOptions = [
  {
    value: "Clothes, shoes, and individual Items",
    label: "Clothes, shoes, and individual Items",
  },
  {
    value: "Historic and Regional Attire",
    label: "Historic and Regional Attire",
  },
  { value: "Digital Painting", label: "Digital Painting" },
];

export const ThreeDAnimationOptions = [
  { value: "Isometric 3D Options", label: "Isometric 3D Options" },
  { value: "Motion Graphics", label: "Motion Graphics" },
  { value: "Character Animation", label: "Character Animation" },
  { value: "3D Sculptures and Statues", label: "3D Sculptures and Statues" },
];

export const CAMERAPERSPECTIVEDATA = [
  {
    id: 1,
    imgsrc: `${IMAGE_URL}/models/highangle.png`,
    title: "High Angle",
  },
  {
    id: 2,
    imgsrc: `${IMAGE_URL}/models/below angle.png`,
    title: "Below",
  },
  {
    id: 3,
    imgsrc: `${IMAGE_URL}/models/lowangle.png`,
    title: "Low Angle",
  },
  {
    id: 4,
    imgsrc: `${IMAGE_URL}/models/aboveangle.png`,
    title: "Above",
  },
  {
    id: 5,
    imgsrc: `${IMAGE_URL}/models/overhead.png`,
    title: "Overhead",
  },
  // {
  //   id: 6,
  //   imgsrc: `${IMAGE_URL}/models/macroshot.png`,
  //   title: "Macro Shot",
  // },
  {
    id: 6,
    imgsrc: `${IMAGE_URL}/models/wideangle.png`,
    title: "Wide Angle",
  },
  // {
  //   id: 8,
  //   imgsrc: `${IMAGE_URL}/models/closeup.png`,
  //   title: "Close Up",
  // },
];

export const CAMERAFILTERSDATA = [
  {
    id: 1,
    imgsrc: `${IMAGE_URL}/models/polaroid.png`,
    title: "Polaroid",
  },
  {
    id: 2,
    imgsrc: `${IMAGE_URL}/models/cctv.png`,
    title: "CCTV",
  },
  {
    id: 3,
    imgsrc: `${IMAGE_URL}/models/solarized.png`,
    title: "Solarized",
  },
  {
    id: 4,
    imgsrc: `${IMAGE_URL}/models/toned.png`,
    title: "Toned",
  },
  {
    id: 5,
    imgsrc: `${IMAGE_URL}/models/black&white.png`,
    title: "Black and White",
  },
  {
    id: 6,
    imgsrc: `${IMAGE_URL}/models/infrared.png`,
    title: "Infrared",
  },
  {
    id: 7,
    imgsrc: `${IMAGE_URL}/models/cooltone.png`,
    title: "Cool Tone",
  },
  {
    id: 8,
    imgsrc: `${IMAGE_URL}/models/warmtone.png`,
    title: "Warm Tone",
  },
];

export const SHUTTERSPEEDDATA = [
  {
    id: 1,
    imgsrc: `${IMAGE_URL}/models/fastshutter.png`,
    title: "Fast Shutter",
  },
  {
    id: 2,
    imgsrc: `${IMAGE_URL}/models/slowshutter.png`,
    title: "Slow Shutter",
  },
  {
    id: 3,
    imgsrc: `${IMAGE_URL}/models/medium shutter.png`,
    title: "Medium Shutter",
  },
];

export const LIGHTINGOPTIONSDATA = [
  {
    id: 1,
    imgsrc: `${IMAGE_URL}/models/backlighting.png`,
    title: "Backlighting",
  },
  {
    id: 2,
    imgsrc: `${IMAGE_URL}/models/dramatic.png`,
    title: "Dramatic",
  },
  {
    id: 3,
    imgsrc: `${IMAGE_URL}/models/goldenhour.png`,
    title: "Golden Hour",
  },
  {
    id: 4,
    imgsrc: `${IMAGE_URL}/models/harshlighting.png`,
    title: "Harsh",
  },
  {
    id: 5,
    imgsrc: `${IMAGE_URL}/models/longexposure.png`,
    title: "Long Time Exposure",
  },
  {
    id: 6,
    imgsrc: `${IMAGE_URL}/models/low lighting.png`,
    title: "Low Lighting",
  },
  {
    id: 7,
    imgsrc: `${IMAGE_URL}/models/studio.png`,
    title: "Studio",
  },
  {
    id: 8,
    imgsrc: `${IMAGE_URL}/models/multiexposure.png`,
    title: "Multi Exposure",
  },
  {
    id: 9,
    imgsrc: `${IMAGE_URL}/models/surreal.png`,
    title: "Surreal",
  },
];

export const IMAGESTYLEDATA = [
  {
    id: 1,
    imgsrc: `${IMAGE_URL}/models/photographic.png`,
    title: "Photographic",
    key: "photographic",
  },
  {
    id: 2,
    imgsrc: `${IMAGE_URL}/models/3Dmodal.png`,
    title: "3D Model",
    key: "3d-model",
  },
  {
    id: 3,
    imgsrc: `${IMAGE_URL}/models/analogfilm.png`,
    title: "Analog Film",
    key: "analog-film",
  },
  {
    id: 4,
    imgsrc: `${IMAGE_URL}/models/digitalart.png`,
    title: "Digital Art",
    key: "digital-art",
  },
  {
    id: 5,
    imgsrc: `${IMAGE_URL}/models/enhance.png`,
    title: "Enhance",
    key: "enhance",
  },
  {
    id: 6,
    imgsrc: `${IMAGE_URL}/models/anime.png`,
    title: "Anime",
    key: "anime",
  },
  {
    id: 7,
    imgsrc: `${IMAGE_URL}/models/fantasyart.png`,
    title: "Fantasy Art",
    key: "fantasy-art",
  },
  {
    id: 8,
    imgsrc: `${IMAGE_URL}/models/comicbook.png`,
    title: "Comic Book",
    key: "comic-book",
  },
  {
    id: 9,
    imgsrc: `${IMAGE_URL}/models/cenematic.png`,
    title: "Cenematic",
    key: "cinematic",
  },
  {
    id: 10,
    imgsrc: `${IMAGE_URL}/models/lineart.png`,
    title: "Line Art",
    key: "line-art",
  },
  {
    id: 11,
    imgsrc: `${IMAGE_URL}/models/isometric.png`,
    title: "Isometric",
    key: "isometric",
  },
  {
    id: 12,
    imgsrc: `${IMAGE_URL}/models/neopunk.png`,
    title: "Neo Punk",
    key: "neon-punk",
  },
  {
    id: 13,
    imgsrc: `${IMAGE_URL}/models/pixelart.png`,
    title: "Pixel Art",
    key: "pixel-art",
  },
  {
    id: 14,
    imgsrc: `${IMAGE_URL}/models/lowpoly.png`,
    title: "Low Poly",
    key: "low-poly",
  },
  {
    id: 15,
    imgsrc: `${IMAGE_URL}/models/origami.png`,
    title: "Origami",
    key: "origami",
  },
  {
    id: 16,
    imgsrc: `${IMAGE_URL}/models/tiletexture.png`,
    title: "Tile",
    key: "tile-texture",
  },
  {
    id: 17,
    imgsrc: `${IMAGE_URL}/models/modellingcompound.png`,
    title: "Modelling Compound",
    key: "modeling-compound",
  },
];

export const SOCIAL_MEDIA = [
  {
    id: nanoid(),
    imgsrc: `${IMAGE_URL}/assets/images/brand/social/facebook.svg`,
    value: "facebook",
  },
  {
    id: nanoid(),
    imgsrc: `${IMAGE_URL}/assets/images/brand/social/instagram.svg`,
    value: "instagram",
  },
  {
    id: nanoid(),
    imgsrc: `${IMAGE_URL}/assets/images/brand/social/linkedin.svg`,
    value: "linkedin",
  },
  {
    id: nanoid(),
    imgsrc: `${IMAGE_URL}/assets/images/brand/social/twitter.svg`,
    value: "twitter",
  },
  {
    id: nanoid(),
    imgsrc: `${IMAGE_URL}/assets/images/brand/social/pinterest.svg`,
    value: "pinterest",
  },
];

export const IMAGE_SIZE = [
  {
    id: nanoid(),
    width: "64.12px",
    height: "64.12px",
    title: "Square",
    diamension: "1080*1080",
  },
  {
    id: nanoid(),
    width: "81.79px",
    height: "49.07px",
    title: "Landscape",
    diamension: "1200*628",
  },
  {
    id: nanoid(),
    width: "64.12px",
    height: "80.48px",
    title: "Portrait",
    diamension: "1080*1350",
  },
  {
    id: nanoid(),
    width: "54.12px",
    height: "80.48px",
    title: "Story",
    diamension: "1080*1920",
  },
  {
    id: nanoid(),
    width: "36.79px",
    height: "61.31px",
    title: "Pin",
    diamension: "1000*1500",
  },
];
export const INSTAGRAM_IMAGE_SIZE = [
  {
    id: nanoid(),
    width: "64.12px",
    height: "64.12px",
    title: "Square",
    diamension: "1080*1080",
  },
  {
    id: nanoid(),
    width: "64.12px",
    height: "80.48px",
    title: "Portrait",
    diamension: "1080*1350",
  },
  {
    id: nanoid(),
    width: "64.12px",
    height: "49.07px",
    title: "Landscape",
    diamension: "1080*566",
  },
  {
    id: nanoid(),
    width: "45.15px",
    height: "80.48px",
    title: "Story",
    diamension: "1080*1920",
  },
];

export const FACEBOOK_IMAGE_SIZE = [
  {
    id: nanoid(),
    width: "81.79px",
    height: "81.79px",
    title: "Square",
    diamension: "1200*1200",
  },
  {
    id: nanoid(),
    width: "49.07px",
    height: "81.79px",
    title: "Portrait",
    diamension: "630*1200",
  },
  {
    id: nanoid(),
    width: "81.79px",
    height: "49.07px",
    title: "Landscape",
    diamension: "1200*630",
  },
  {
    id: nanoid(),
    width: "64.12px",
    height: "80.48px",
    title: "Story",
    diamension: "1080*1920",
  },
  // {
  //   id: nanoid(),
  //   width: "80.48px",
  //   height: "30.48px",
  //   title: "Cover",
  //   diamension: "1128*191",
  // },
];

export const TWITTER_IMAGE_SIZE = [
  {
    id: nanoid(),
    width: "64.12px",
    height: "64.12px",
    title: "Square",
    diamension: "1080*1080",
  },
  {
    id: nanoid(),
    width: "64.12px",
    height: "80.48px",
    title: "Portrait",
    diamension: "1080*1350",
  },
  {
    id: nanoid(),
    width: "81.79px",
    height: "49.07px",
    title: "Landscape",
    diamension: "1600*900",
  },
  // {
  //   id: nanoid(),
  //   width: "80.48px",
  //   height: "30.48px",
  //   title: "Cover",
  //   diamension: "1128*191",
  // },
];

export const LINKEDIN_IMAGE_SIZE = [
  {
    id: nanoid(),
    width: "64.12px",
    height: "64.12px",
    title: "Square",
    diamension: "1080*1080",
  },
  {
    id: nanoid(),
    width: "64.12px",
    height: "80.48px",
    title: "Portrait",
    diamension: "627*1200",
  },
  {
    id: nanoid(),
    width: "80.48px",
    height: "64.12px",
    title: "Landscape",
    diamension: "1200*627",
  },
  // {
  //   id: nanoid(),
  //   width: "80.48px",
  //   height: "30.48px",
  //   title: "Cover",
  //   diamension: "1128*191",
  // },
];
export const PINTREST_IMAGE_SIZE = [
  {
    id: nanoid(),
    width: "64.12px",
    height: "64.12px",
    title: "Square",
    diamension: "1080*1080",
  },
  {
    id: nanoid(),
    width: "64.12px",
    height: "80.48px",
    title: "Portrait",
    diamension: "735*1102",
  },
  {
    id: nanoid(),
    width: "81.79px",
    height: "49.07px",
    title: "Landscape",
    diamension: "1080*556",
  },
  // {
  //   id: nanoid(),
  //   width: "80.48px",
  //   height: "30.48px",
  //   title: "Cover",
  //   diamension: "1128*191",
  // },
];
export const FOCUS_ELEMENT = [
  {
    id: 1,
    title: "People",
  },
  {
    id: 2,
    title: "Object",
  },
  {
    id: 3,
    title: "Environmental",
  },
];

export const CONTEXT_IMAGE = [
  {
    id: 1,
    title: "Indian",
  },
  {
    id: 2,
    title: "Global",
  },
];

export const TARGRTGROUP_GENDER = [
  {
    id: 1,
    name: "Male",
  },
  {
    id: 2,
    name: "Female",
  },
  {
    id: 3,
    name: "All",
  },
];

export const SectionOptions = [
  { value: "Complete Song", label: "Complete Song" },
  { value: "Chorus", label: "Chorus" },
  { value: "Verse", label: "Verse" },
  { value: "Pre-chorus", label: "Pre-chorus" },
  { value: "Bridge", label: "Bridge" },
  { value: "Intro", label: "Intro" },
  { value: "Outro", label: "Outro" },
  { value: "Interlude", label: "Interlude" },
  { value: "Hook", label: "Hook" },
  { value: "Coda", label: "Coda" },
  { value: "Tag", label: "Tag" },
];

export const rhymesOptions = [
  { label: "Exact Rhymes", value: "RHYME" },
  { label: "Synonyms", value: "SYNONYM" },
  { label: "Antonyms", value: "ANTONYM" },
];

export const LineOptions = [
  { value: "One Line", label: "One Line" },
  { value: "Two Line", label: "Two Line" },
  { value: "Three Line", label: "Three Line" },
];
export const WriteOptions = [
  { value: "One Verse", label: "One Verse" },
  { value: "Two Verse", label: "Two Verse" },
  { value: "Three Verse", label: "Three Verse" },
];

export const Format = [
  { value: "Structured verses", label: "Structured verses" },
  { value: "Call and response", label: "Call and response" },
  { value: "Free verse", label: "Free verse" },
  { value: "Rap verses", label: "Rap verses" },
  { value: "Rhyming couplets", label: "Rhyming couplets" },
  { value: "Chorus-Verse-Chorus", label: "Chorus-Verse-Chorus" },
  { value: "AABA", label: "AABA" },
  {
    value: "ABAB (Alternating verses and choruses)",
    label: "ABAB (Alternating verses and choruses)",
  },
  { value: "AAA (All verses)", label: "AAA (All verses)" },
  { value: "Verse-Refrain", label: "Verse-Refrain" },
];

export const Persona = [
  { value: "Romantic poet", label: "Romantic poet" },
  { value: "Witty songwriter", label: "Witty songwriter" },
  { value: "Reflective storyteller", label: "Reflective storyteller" },
  { value: "Political commentator", label: "Political commentator" },
  { value: "Inspirational leader", label: "Inspirational leader" },
  { value: "Nostalgic Narrator", label: "Nostalgic Narrator" },
  { value: "Futuristic Visionary", label: "Futuristic Visionary" },
  { value: "Spiritual Guru", label: "Spiritual Guru" },
  { value: "Social Activist", label: "Social Activist" },
  { value: "Philosophical Thinker", label: "Philosophical Thinker" },
  { value: "Party Enthusiast", label: "Party Enthusiast" },
  { value: "Devotional Singer", label: "Devotional Singer" },
];

export const Tone = [
  { value: "Sentimental", label: "Sentimental" },
  { value: "Energetic", label: "Energetic" },
  { value: "Melancholic", label: "Melancholic" },
  { value: "Humorous", label: "Humorous" },
  { value: "Inspirational", label: "Inspirational" },
  { value: "Happy", label: "Happy" },
  { value: "Sad", label: "Sad" },
  { value: "Angry", label: "Angry" },
  { value: "Peaceful", label: "Peaceful" },
  { value: "Excited", label: "Excited" },
  { value: "Romantic", label: "Romantic" },
  { value: "Nostalgic", label: "Nostalgic" },
  { value: "Serious", label: "Serious" },
];

export const Task = [
  { value: "Classic rock song", label: "Classic Rock song" },
  { value: "Modern pop", label: "Modern pop" },
  { value: "Folk music", label: "Folk music" },
  { value: "Hip-hop flow", label: "Hip-hop flow" },
  { value: "Jazz standard", label: "Jazz standard" },
];

export const Genre = [
  { value: "Bollywood", label: "Bollywood" },
  { value: "Pop", label: "Pop" },
  { value: "Indian Classical", label: "Indian Classical" },
  { value: "Folk", label: "Folk" },
  { value: "Ghazal", label: "Ghazal" },
  { value: "Sufi", label: "Sufi" },
  { value: "Hip-Hop", label: "Hip-Hop" },
  { value: "Indie", label: "Indie" },
  { value: "Rock", label: "Rock" },
  {
    value: "Electronic Dance Music (EDM)",
    label: "Electronic Dance Music (EDM)",
  },
  { value: "Jazz", label: "Jazz" },
  { value: "Blues", label: "Blues" },
  { value: "Qawwali", label: "Qawwali" },
  { value: "Bhangra", label: "Bhangra" },
  { value: "Devotional", label: "Devotional" },
];

export const Mood = [
  { value: "Sentimental", label: "Sentimental" },
  { value: "Energetic", label: "Energetic" },
  { value: "Inspirational", label: "Inspirational" },
  { value: "Romantic", label: "Romantic" },
  { value: "Melancholic", label: "Melancholic" },
  { value: "Humorous", label: "Humorous" },
  { value: "Peaceful", label: "Peaceful" },
  { value: "Nostalgic", label: "Nostalgic" },
  { value: "Hopeful", label: "Hopeful" },
  { value: "Excited", label: "Excited" },
];

export const Theme = [
  { value: "Love Story", label: "Love Story" },
  { value: "Celebration", label: "Celebration" },
  { value: "Social Commentary", label: "Social Commentary" },
  {
    value: "Historical/Mythological Tales",
    label: "Historical/Mythological Tales",
  },
  { value: "Nature", label: "Nature" },
  { value: "Adventure", label: "Adventure" },
  { value: "Friendship", label: "Friendship" },
  { value: "Heartbreak", label: "Heartbreak" },
  { value: "Victory", label: "Victory" },
  { value: "Struggle", label: "Struggle" },
];

export const Language = [
  { value: "Hindi", label: "Hindi" },
  { value: "English", label: "English" },
  { value: "Hindi + English", label: "Hindi + English" },
];

export const TGLanguage = [
  { value: "Not Applicable", label: "Not Applicable" },
  { value: "Hindi", label: "Hindi" },
  { value: "English", label: "English" },
  { value: "Marathi", label: "Marathi" },
  { value: "Gujrati", label: "Gujrati" },
  { value: "Bengali", label: "Bengali" },
  { value: "Punjabi", label: "Punjabi" },
  { value: "Tamil", label: "Tamil" },
  { value: "Telugu", label: "Telugu" },
  { value: "Kannada", label: "Kannada" },
  { value: "Malayalam", label: "Malayalam" },
];

export const TargetAudience = [
  { value: "Young Adults", label: "Young Adults" },
  { value: "Adults", label: "Adults" },
  { value: "Seniors", label: "Seniors" },
  { value: "Children", label: "Children" },
  { value: "Teenagers", label: "Teenagers" },
  { value: "All Ages", label: "All Ages" },
];

export const Style = [
  { value: "Pop", label: "Pop" },
  { value: "Rock", label: "Rock" },
  { value: "Country", label: "Country" },
  { value: "Rap", label: "Rap" },
  { value: "Classical", label: "Classical" },
  { value: "Jazz", label: "Jazz" },
  { value: "Blues", label: "Blues" },
  { value: "R&B", label: "R&B" },
  { value: "Electronic", label: "Electronic" },
  { value: "Folk", label: "Folk" },
];

export const RhymeScheme = [
  { value: "AABB (Couplets)", label: "AABB (Couplets)" },
  { value: "ABAB (Alternate Rhyme)", label: "ABAB (Alternate Rhyme)" },
  { value: "ABCB (Ballad Stanza)", label: "ABCB (Ballad Stanza)" },
  { value: "ABBA (Envelope Rhyme)", label: "ABBA (Envelope Rhyme)" },
  { value: "ABCABC (Sestet)", label: "ABCABC (Sestet)" },
  { value: "No Rhyme (Free Verse)", label: "No Rhyme (Free Verse)" },
];

export const TargetListeners = [
  { value: "Young Adults", label: "Young Adults" },
  { value: "Adults", label: "Adults" },
  { value: "Seniors", label: "Seniors" },
  { value: "Children", label: "Children" },
  { value: "Teenagers", label: "Teenagers" },
  { value: "All Ages", label: "All Ages" },
];
